export const MAP_LOADED = "MAP_LOADED";
export const RESET_MAP_LOADED = "RESET_MAP_LOADED";

export const LOCATION_FOUND = "LOCATION_FOUND";
export const LOCATION_ERROR = "LOCATION_ERROR";
export const SET_END_LOCATION = "SET_END_LOCATION";
export const UNSELECT_LOCATION = "UNSELECT_LOCATION";

export const FINISHED_TUTORIAL = "FINISHED_TUTORIAL";

export const SET_LOADING = "SET_LOADING";
export const RESET_PRICES = "RESET_PRICES";

export const FETCH_PRICES = "FETCH_PRICES";
export const FETCH_PRICES_SUCCESS = "FETCH_PRICES_SUCCESS";
export const FETCH_PRICES_ERROR = "FETCH_PRICES_ERROR";

export const SEND_FEEDBACK = "SEND_FEEDBACK";
export const SEND_FEEDBACK_SUCCESS = "SEND_FEEDBACK_SUCCESS";
export const SEND_FEEDBACK_ERROR = "SEND_FEEDBACK_ERROR";

export const ADD_ADDRESS = "ADD_ADDRESS";

export const CREATE_SHARE_LINK = "CREATE_SHARE_LINK";
export const CREATE_SHARE_LINK_SUCCESS = "CREATE_SHARE_LINK_SUCCESS";
export const CREATE_SHARE_LINK_ERROR = "CREATE_SHARE_LINK_ERROR";
export const FETCH_SHARE_LINK = "FETCH_SHARE_LINK";
export const FETCH_SHARE_LINK_SUCCESS = "FETCH_SHARE_LINK_SUCCESS";
export const FETCH_SHARE_LINK_ERROR = "FETCH_SHARE_LINK_ERROR";

export const FETCH_PROMO_CODES = "FETCH_PROMO_CODES";
export const FETCH_PROMO_CODES_SUCCESS = "FETCH_PROMO_CODES_SUCCESS";
export const FETCH_PROMO_CODES_ERROR = "FETCH_PROMO_CODES_ERROR";

export const SEND_LINK = "SEND_LINK";
export const SEND_LINK_SUCCESS = "SEND_LINK_SUCCESS";
export const SEND_LINK_ERROR = "SEND_LINK_ERROR";

export const SET_USER_NOT_NEW = "SET_USER_NOT_NEW";
